### ISSUE TITLE
Unit testing to validate twitter link

### ISSUE THREAD

**Issue by ATLAS2002** [ossguild/Nametaker#22]
### As of now, contributors can add malicious links as their twitter handle, which can negatively affect the user's experience. Adding a unit test to validate the link can prevent it. There is screenshot of the bug attached below:
![bug](https://github.com/ossguild/Nametaker/assets/123821746/06868897-4228-44f7-ba25-987bb5ccdbe5)

**Comment by ATLAS2002** [comment]
@ajax484 can you assign this issue to me? I have already ran some tests with vitest and it seems to be working perfectly... And this would also be my first hacktoberfest contribution :)

**Comment by ajax484** [comment]
Sure I'll do so now

**Comment by ATLAS2002** [comment]
> Sure I'll do so now

Hi @ajax484 I have created a pull request regarding the issue, you might want to check it for review

**Comment by ajax484** [comment]
merged, nice work @ATLAS2002
